### ISSUE TITLE
Post filter and paging

### ISSUE THREAD

**Issue by CCob** [RovoMe/spring-security-acl-mongodb#4]
Hi,  this project looks really interesting.  I'm always on the lookout of a Spring ACL implementation that provides row level security.  The downfall I see in many of them is that the data that comes back from the database is post filtered with only the rows the authenticated principal has access to.  The issue I have had in the past with this is that it ruins database paging.  

Does this library augment mongo queries with the desired permission checks when querying collections before the call is made to retrieve a collection, or is this done as a post filter mechanism?

Thanks

**Comment by RovoMe** [comment]
Hi,

the only Mongo queries executed via MongoTemplate are the ones listed below: 

```
Criteria where = Criteria.where("instanceId").in(objectIds).and("className").in(types);
List<MongoAcl> foundAcls = 
  mongoTemplate.find(query(where)
    .with(new Sort(Sort.Direction.ASC, "instanceId", "permissions.position")), MongoAcl.class);
```

The query above is performed to [lookup a batch of ObjectIdentities](https://github.com/RovoMe/spring-security-acl-mongodb/blob/master/src/main/java/org/springframework/security/acls/mongodb/BasicLookupStrategy.java#L180) from the database.

The query below just loads a [parent ACL](https://github.com/RovoMe/spring-security-acl-mongodb/blob/master/src/main/java/org/springframework/security/acls/mongodb/BasicLookupStrategy.java#L226) if it was not loaded before and therefore is available within the cache.

```
parentAcl = mongoTemplate.findById(mongoAcl.getParentId(), MongoAcl.class);
```

The parent ACL can be used to inherit permissions and to avoid having to specify the same permissions on objects of a certain parent "category" to specify them over and over again.

The code follows the original SQL based `BasicLookupStrategy` as much as possible. As the SQL strategy, however, performs a join over 4 tables on cache-misses, where only the ObjectIdentity is the relevant lookup part, the MongoDB port uses the strength of NoSQL databases and not having to rely on normalized table/collection forms to retrieve the whole data at once. This, however, also comes at its price compared to the SQL based version in that you probably store some redundant data and therefore increase the overall size of the entry compared to the normalized form of the SQL table entries. 

As you can hopefully see the first query returns all available ObjectIdentity entries for the given list of identities to lookup, if available. This [lookup is performed in chunks](https://github.com/RovoMe/spring-security-acl-mongodb/blob/master/src/main/java/org/springframework/security/acls/mongodb/BasicLookupStrategy.java#L143-L150) where `batchSize` is set to 50 by default. The query itself, though, does not yet make use of pagination. Using pagination (or even a streaming approach) should be possible in general though. The initial list of object identities to lookup should be sorted by ID beforehand in that case as well to speed up lookup times even further.

The retrieved [ACLs are post-filtered](https://github.com/RovoMe/spring-security-acl-mongodb/blob/master/src/main/java/org/springframework/security/acls/mongodb/BasicLookupStrategy.java#L195) once the loaded data is converted to an ACL object representation. The ACL is added into the returned result set only if the provided SIDs are either the owner of the ACL or defined within the permission list.

Hope this answers your questions.

**Comment by CCob** [comment]
Great.  Thanks for the detailed explanation.
